spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: 'triangleStick0628'
    password: 'wwazivsmqqogncnw'
    properties:
      mail:
        smtp:
          starttls.enable: true
          auth: true

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace